
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[28,)"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="http://my.issue.tracker/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="explorercraft" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="3.2.2" #mandatory
 # A display name for the mod
displayName="Explorercraft" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://minecraft.curseforge.com/projects/explorercraft-worldexpansion" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="logo.png" #optional
# A text field displayed in the mod UI
credits="TheVertExplorer - Created some art assets for the Cymru Expansion, Luber_Pasaya - Banners, EvilMinecraft Team of Yesteryear for ancient assets/code!, BronGhast014 - Models from Creatures++ Datapack" #optional
# A text field displayed in the mod UI
authors="Zathrox" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
A mod based on adding new Exploration and Adventures.
Grab yourself a sleeping bag, campfire and a map and venture into the world!/
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.explorercraft]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[28,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.explorercraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"